# Generated by Django 3.1.2 on 2020-10-14 15:04

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import BtreeGinExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        BtreeGinExtension(),
        migrations.AlterField(
            model_name='searchresult',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='searchresult',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title', 'description'], name='search_resu_title_b10125_gin'),
        ),
    ]
